name: ci
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 1 * * 0'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      -
        name: Create docker cache folder
        run: mkdir -p /tmp/docker
      -
        name: Restore docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('builder.Dockerfile') }}
      -
        name: Build docker builder-image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: builder.Dockerfile
          tags: cproject-builder:latest
          outputs: type=docker,dest=/tmp/docker/${{ runner.os }}-builder-image.tar

  build-and-test:
      runs-on: ubuntu-latest
      needs: docker-build
      steps:
        - uses: actions/checkout@v4
        - uses: docker/setup-buildx-action@v3
        -
          name: Restore docker image
          id: cache-docker
          uses: actions/cache@v4
          with:
            path: /tmp/docker
            key: ${{ runner.os }}-docker-${{ hashFiles('builder.Dockerfile') }}
        -
          name: Load image
          run: |
            docker load --input /tmp/docker/${{ runner.os }}-builder-image.tar
            docker image ls -a
        -
          name: Build library
          run: |
            docker run \
              --rm \
              --platform linux/amd64 \
              --workdir /builder/mnt \
              -v ${{ github.workspace }}:/builder/mnt \
              cproject-builder:latest \
              /bin/bash -c "rm -rf build; cmake -B build; cmake --build build"